package measurements;

public class Dimensions {

    //Comprimento length, largura width e altura height

    private float length, width, height;

    public Dimensions(float length, float width, float height) {
        this.length = length;
        this.width = width;
        this.height = height;
    }

    public Dimensions(float height) {
        this.height = height;
    }

    public float getLength() {
        return length;
    }

    public float getWidth() {
        return width;
    }

    public float getHeight() {
        return height;
    }

    //comparing the sizes of the objects
     public boolean compareSizes(Dimensions dimensionCargo, Dimensions dimensionsVehicle){
        if (dimensionCargo.calculateVector() <= dimensionsVehicle.calculateVector()){
            return true;
        }
        return false;
    }

    /*calculating the size of the vectors generated by each object in order
    to know if they fit inside the other*/
    public double calculateVector(){
        return Math.pow(this.getHeight(), 2)
                + Math.pow(this.getLength(), 2)
                + Math.pow(this.getWidth(), 2);
    }
    @Override
    public String toString() {
        return "length=" + length +
                ", width=" + width +
                ", height=" + height;
    }
}
